---
apiVersion: v1
kind: Pod
metadata:
    name: fbserver
    labels:
        app: facebook
        env: lab

spec: 
    containers:
        - name: fbcont
          image: tomcat
kubectl explain deployment | head -n3
kind

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: httpd-frontend
  template:
    metadata:
      labels:
        name: httpd-frontend
    spec:
      containers:
      - name: httpd-frontend
        image: httpd:2.4-alpine